@baseUrl = http://localhost:4000/api/v1
@contentType = application/json

### 1. Login as Police Chief
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "username": "sheriff.john",
  "password": "Password123!"
}

### Auth Token
@authToken = {{login.response.body.data.accessToken}}

### 3. Create a new task
# @name createTask
POST {{baseUrl}}/tasks
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "task_name": "Interview Witness",
  "content": "Interview John Doe about the incident",
  "start_date": "2025-07-15T09:00:00.000Z",
  "due_date": "2025-07-17T17:00:00.000Z",
  "case_id": "CASE-002",
  "username": "officer.jane"
}
