import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1751449699953 implements MigrationInterface {
    name = 'Migrations1751449699953'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`sentence\` (\`sentence_id\` varchar(255) NOT NULL, \`sentence_type\` varchar(255) NOT NULL, \`duration\` varchar(255) NULL, \`condition\` varchar(255) NULL, \`sentencing_date\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, \`caseResultCaseResultId\` varchar(255) NULL, PRIMARY KEY (\`sentence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timelines\` (\`timeline_id\` varchar(255) NOT NULL, \`case_result_id\` varchar(255) NOT NULL, \`start_time\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`end_time\` timestamp NULL, \`attached_file\` json NULL, \`notes\` varchar(255) NULL, \`activity\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseResultCaseResultId\` varchar(255) NULL, PRIMARY KEY (\`timeline_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_result\` (\`case_result_id\` varchar(255) NOT NULL, \`report_time\` timestamp NOT NULL, \`report_analyst\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`identify_motive\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, PRIMARY KEY (\`case_result_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission\` (\`permission_id\` varchar(255) NOT NULL, \`description\` text NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles_permissions\` (\`role_id\` varchar(255) NOT NULL, \`permission_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`role_id\`, \`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`role_id\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`investigation_plan\` (\`investigation_plan_id\` varchar(255) NOT NULL, \`deadline_date\` timestamp NOT NULL, \`result\` text NULL, \`status\` varchar(255) NULL, \`create_at\` timestamp NOT NULL, \`plan_content\` text NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, \`createdOfficerIdUsername\` varchar(255) NULL, PRIMARY KEY (\`investigation_plan_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`indictments\` (\`indictment_id\` varchar(255) NOT NULL, \`content\` varchar(255) NOT NULL, \`issued_at\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`prosecutionProsecutionId\` varchar(255) NULL, PRIMARY KEY (\`indictment_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`prosecution\` (\`prosecution_id\` varchar(255) NOT NULL, \`decision\` varchar(255) NOT NULL, \`decision_date\` timestamp NOT NULL, \`reason\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, \`userUsername\` varchar(255) NULL, PRIMARY KEY (\`prosecution_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users_cases\` (\`user_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`user_id\`, \`case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`question\` (\`question_id\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`answer\` text NULL, \`reliability\` float NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`interviewInterviewId\` varchar(255) NULL, \`userUsername\` varchar(255) NULL, PRIMARY KEY (\`question_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`username\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`avatar_url\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`phone_number\` varchar(255) NOT NULL, \`create_at\` datetime NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`roleRoleId\` varchar(255) NULL, PRIMARY KEY (\`username\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`witness\` (\`witness_id\` int NOT NULL AUTO_INCREMENT, \`fullname\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`statement\` text NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, PRIMARY KEY (\`witness_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`witnesses_interviews\` (\`interview_id\` varchar(255) NOT NULL, \`witness_id\` int NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`interview_id\`, \`witness_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`interviews\` (\`interview_id\` varchar(255) NOT NULL, \`type_interviewee\` varchar(255) NOT NULL, \`location\` varchar(255) NOT NULL, \`attached_file\` varchar(255) NOT NULL, \`start_time\` timestamp NOT NULL, \`end_time\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`interviewer_id\` varchar(255) NULL, \`investigation_plan_id\` varchar(255) NULL, PRIMARY KEY (\`interview_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`victim_interview\` (\`victim_id\` varchar(255) NOT NULL, \`interview_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`victim_id\`, \`interview_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`victims\` (\`victim_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`injuries\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, PRIMARY KEY (\`victim_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports_victims\` (\`report_id\` varchar(255) NOT NULL, \`victim_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`report_id\`, \`victim_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`report_id\` varchar(255) NOT NULL, \`type_report\` varchar(255) NOT NULL, \`severity\` varchar(255) NOT NULL, \`incident_date\` timestamp NOT NULL, \`description\` varchar(255) NULL, \`case_location\` varchar(255) NOT NULL, \`reported_at\` timestamp NOT NULL, \`reporter_location\` varchar(255) NOT NULL, \`reporter_fullname\` varchar(255) NOT NULL, \`reporter_email\` varchar(255) NOT NULL, \`reporter_phone_number\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`status\` varchar(255) NOT NULL, \`userUsername\` varchar(255) NULL, \`caseCaseId\` varchar(255) NULL, PRIMARY KEY (\`report_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`suspect\` (\`suspect_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`national\` varchar(255) NOT NULL, \`gender\` varchar(255) NOT NULL, \`dob\` timestamp NOT NULL, \`identification\` varchar(255) NOT NULL, \`phone_number\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`address\` varchar(255) NOT NULL, \`catch_time\` datetime NOT NULL, \`notes\` text NULL, \`status\` varchar(255) NOT NULL, \`mugshot_url\` varchar(255) NULL, \`fingerprints_hash\` varchar(255) NOT NULL, \`health_status\` varchar(255) NOT NULL, \`caseCaseId\` varchar(255) NULL, \`reportReportId\` varchar(255) NULL, PRIMARY KEY (\`suspect_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`evidences_suspects\` (\`evidence_id\` varchar(255) NOT NULL, \`suspect_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`, \`suspect_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`forensic_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`lab_name\` varchar(255) NOT NULL, \`report\` varchar(255) NOT NULL, \`received_at\` datetime NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`measure_surveys\` (\`measure_survey_id\` varchar(255) NOT NULL, \`type_name\` varchar(255) NOT NULL, \`source\` varchar(255) NULL, \`result\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`evidenceEvidenceId\` varchar(255) NULL, PRIMARY KEY (\`measure_survey_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`physical_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`image_url\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`record_info\` (\`record_info_id\` varchar(255) NOT NULL, \`type_name\` varchar(255) NOT NULL, \`source\` varchar(255) NOT NULL, \`date_collected\` timestamp NOT NULL, \`summary\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`evidenceEvidenceId\` varchar(255) NULL, PRIMARY KEY (\`record_info_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warrant_result\` (\`warrant_result_id\` varchar(255) NOT NULL, \`police_response\` varchar(255) NOT NULL, \`location\` varchar(255) NOT NULL, \`notes\` varchar(255) NOT NULL, \`time_active\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`warrantWarrantId\` varchar(255) NULL, PRIMARY KEY (\`warrant_result_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warrant\` (\`warrant_id\` varchar(255) NOT NULL, \`warrant_name\` varchar(255) NOT NULL, \`attached_file\` json NULL, \`time_publish\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, PRIMARY KEY (\`warrant_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`evidences\` (\`evidence_id\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`collected_at\` timestamp NOT NULL, \`current_location\` varchar(255) NOT NULL, \`attach_file\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, \`userUsername\` varchar(255) NULL, \`reportReportId\` varchar(255) NULL, \`warrantWarrantId\` varchar(255) NULL, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cases_evidences\` (\`case_id\` varchar(255) NOT NULL, \`evidence_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`case_id\`, \`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case\` (\`case_id\` varchar(255) NOT NULL, \`case_number\` int NOT NULL, \`type_case\` varchar(255) NOT NULL, \`severity\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`create_at\` datetime NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`arrest\` (\`arrest_id\` varchar(255) NOT NULL, \`suspect_miranda_signature\` varchar(255) NULL, \`arrest_start_time\` timestamp NOT NULL, \`arrest_end_time\` timestamp NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`caseCaseId\` varchar(255) NULL, \`suspectSuspectId\` varchar(255) NULL, PRIMARY KEY (\`arrest_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`digital_inverts\` (\`evidence_id\` varchar(255) NOT NULL, \`device_type\` varchar(255) NOT NULL, \`analyst_tool\` varchar(255) NOT NULL, \`result\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`financial_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`sentence\` ADD CONSTRAINT \`FK_dffd1c80b8fbed1c13be3574990\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sentence\` ADD CONSTRAINT \`FK_f2c8e38cd954b09b905f3f3a41b\` FOREIGN KEY (\`caseResultCaseResultId\`) REFERENCES \`case_result\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timelines\` ADD CONSTRAINT \`FK_c68fc59db25dc3ef014846e2c47\` FOREIGN KEY (\`caseResultCaseResultId\`) REFERENCES \`case_result\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_result\` ADD CONSTRAINT \`FK_3b10801e5e42440921e98c8a13e\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` ADD CONSTRAINT \`FK_7d2dad9f14eddeb09c256fea719\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` ADD CONSTRAINT \`FK_337aa8dba227a1fe6b73998307b\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permission\`(\`permission_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` ADD CONSTRAINT \`FK_92c1150980585ee7101b6ed070b\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` ADD CONSTRAINT \`FK_d9cb669d0d27e010b2de18c0c26\` FOREIGN KEY (\`createdOfficerIdUsername\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`indictments\` ADD CONSTRAINT \`FK_e878e3d70a2832e213b99d83418\` FOREIGN KEY (\`prosecutionProsecutionId\`) REFERENCES \`prosecution\`(\`prosecution_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecution\` ADD CONSTRAINT \`FK_5bdaf8b238611ba479f191aac28\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecution\` ADD CONSTRAINT \`FK_35e459115b61ef26b5bd7ebf8bd\` FOREIGN KEY (\`userUsername\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_cases\` ADD CONSTRAINT \`FK_b5003f35ff1897c040601e6f94b\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_cases\` ADD CONSTRAINT \`FK_98b89d0b95421aa0ffe4d81e707\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question\` ADD CONSTRAINT \`FK_690af1a3076d6af739aceeb942a\` FOREIGN KEY (\`interviewInterviewId\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question\` ADD CONSTRAINT \`FK_a964c0196f21cf6ffdf994f74f1\` FOREIGN KEY (\`userUsername\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_f32dd66b36a5aa53fc615781bed\` FOREIGN KEY (\`roleRoleId\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witness\` ADD CONSTRAINT \`FK_09e17479124d09dcf7f902ceaed\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` ADD CONSTRAINT \`FK_395823e5b67b06d5febccbe0bfa\` FOREIGN KEY (\`witness_id\`) REFERENCES \`witness\`(\`witness_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` ADD CONSTRAINT \`FK_bd51fb7805ecb70973e357026e4\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_dab087b7d082364ae58637eafbb\` FOREIGN KEY (\`interviewer_id\`) REFERENCES \`users\`(\`username\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_d4ce448ecdb3ea3bba1a418256e\` FOREIGN KEY (\`investigation_plan_id\`) REFERENCES \`investigation_plan\`(\`investigation_plan_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` ADD CONSTRAINT \`FK_6df831d0f480118887381de5a74\` FOREIGN KEY (\`victim_id\`) REFERENCES \`victims\`(\`victim_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` ADD CONSTRAINT \`FK_b35cbf11a70f500cc2adff9c652\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victims\` ADD CONSTRAINT \`FK_c61da41fa239de6dcbc39ae9b25\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` ADD CONSTRAINT \`FK_90a054f200e833bea72c588832b\` FOREIGN KEY (\`victim_id\`) REFERENCES \`victims\`(\`victim_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` ADD CONSTRAINT \`FK_005995a69fa262fcbb618eb6bb1\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_b08c58c743998e27c8d4204a4bd\` FOREIGN KEY (\`userUsername\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_47ccc73d0ef34e721c049cd22c0\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suspect\` ADD CONSTRAINT \`FK_b926db5b6d3e0c1e7bbe97d581e\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suspect\` ADD CONSTRAINT \`FK_e8442da87a0b4a77c2b8bfc268e\` FOREIGN KEY (\`reportReportId\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` ADD CONSTRAINT \`FK_6d92b4c3140e9fda7d72cb9b687\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` ADD CONSTRAINT \`FK_f043d82d1597061ff85f1595286\` FOREIGN KEY (\`suspect_id\`) REFERENCES \`suspect\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`measure_surveys\` ADD CONSTRAINT \`FK_75a5bc8f6420b4aad1a2c36c0fc\` FOREIGN KEY (\`evidenceEvidenceId\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` ADD CONSTRAINT \`FK_312aa4afe21cae3636897e03212\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`record_info\` ADD CONSTRAINT \`FK_f5a88fa892a6c3e71ceae3c9a64\` FOREIGN KEY (\`evidenceEvidenceId\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant_result\` ADD CONSTRAINT \`FK_dbd6d1f4693ac5210271257990e\` FOREIGN KEY (\`warrantWarrantId\`) REFERENCES \`warrant\`(\`warrant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant\` ADD CONSTRAINT \`FK_77dbe1dff8406f4e22028cdd5ea\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_cfd7ec753d5d6c48ccf6a0f9ce4\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_6434b52fc51bf4277faf3fbc05a\` FOREIGN KEY (\`userUsername\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_e0ac0462950cfb31c56d83ff97c\` FOREIGN KEY (\`reportReportId\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_a387811f6b3ad4a91003d446b9c\` FOREIGN KEY (\`warrantWarrantId\`) REFERENCES \`warrant\`(\`warrant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` ADD CONSTRAINT \`FK_89100b6fee543b3f09387a723cf\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` ADD CONSTRAINT \`FK_d19f904c25cf4470e88887751a0\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrest\` ADD CONSTRAINT \`FK_696bc107e49ad9a211f54b808db\` FOREIGN KEY (\`caseCaseId\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrest\` ADD CONSTRAINT \`FK_2d9d75de4eb4341847553e0d70e\` FOREIGN KEY (\`suspectSuspectId\`) REFERENCES \`suspect\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`digital_inverts\` ADD CONSTRAINT \`FK_e5125b808e73f90db7690af2d17\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`financial_invest\` ADD CONSTRAINT \`FK_0adbd65084d113b5117ee21af6a\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`financial_invest\` DROP FOREIGN KEY \`FK_0adbd65084d113b5117ee21af6a\``);
        await queryRunner.query(`ALTER TABLE \`digital_inverts\` DROP FOREIGN KEY \`FK_e5125b808e73f90db7690af2d17\``);
        await queryRunner.query(`ALTER TABLE \`arrest\` DROP FOREIGN KEY \`FK_2d9d75de4eb4341847553e0d70e\``);
        await queryRunner.query(`ALTER TABLE \`arrest\` DROP FOREIGN KEY \`FK_696bc107e49ad9a211f54b808db\``);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` DROP FOREIGN KEY \`FK_d19f904c25cf4470e88887751a0\``);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` DROP FOREIGN KEY \`FK_89100b6fee543b3f09387a723cf\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_a387811f6b3ad4a91003d446b9c\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_e0ac0462950cfb31c56d83ff97c\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_6434b52fc51bf4277faf3fbc05a\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_cfd7ec753d5d6c48ccf6a0f9ce4\``);
        await queryRunner.query(`ALTER TABLE \`warrant\` DROP FOREIGN KEY \`FK_77dbe1dff8406f4e22028cdd5ea\``);
        await queryRunner.query(`ALTER TABLE \`warrant_result\` DROP FOREIGN KEY \`FK_dbd6d1f4693ac5210271257990e\``);
        await queryRunner.query(`ALTER TABLE \`record_info\` DROP FOREIGN KEY \`FK_f5a88fa892a6c3e71ceae3c9a64\``);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` DROP FOREIGN KEY \`FK_312aa4afe21cae3636897e03212\``);
        await queryRunner.query(`ALTER TABLE \`measure_surveys\` DROP FOREIGN KEY \`FK_75a5bc8f6420b4aad1a2c36c0fc\``);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` DROP FOREIGN KEY \`FK_f043d82d1597061ff85f1595286\``);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` DROP FOREIGN KEY \`FK_6d92b4c3140e9fda7d72cb9b687\``);
        await queryRunner.query(`ALTER TABLE \`suspect\` DROP FOREIGN KEY \`FK_e8442da87a0b4a77c2b8bfc268e\``);
        await queryRunner.query(`ALTER TABLE \`suspect\` DROP FOREIGN KEY \`FK_b926db5b6d3e0c1e7bbe97d581e\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_47ccc73d0ef34e721c049cd22c0\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_b08c58c743998e27c8d4204a4bd\``);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` DROP FOREIGN KEY \`FK_005995a69fa262fcbb618eb6bb1\``);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` DROP FOREIGN KEY \`FK_90a054f200e833bea72c588832b\``);
        await queryRunner.query(`ALTER TABLE \`victims\` DROP FOREIGN KEY \`FK_c61da41fa239de6dcbc39ae9b25\``);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` DROP FOREIGN KEY \`FK_b35cbf11a70f500cc2adff9c652\``);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` DROP FOREIGN KEY \`FK_6df831d0f480118887381de5a74\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_d4ce448ecdb3ea3bba1a418256e\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_dab087b7d082364ae58637eafbb\``);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` DROP FOREIGN KEY \`FK_bd51fb7805ecb70973e357026e4\``);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` DROP FOREIGN KEY \`FK_395823e5b67b06d5febccbe0bfa\``);
        await queryRunner.query(`ALTER TABLE \`witness\` DROP FOREIGN KEY \`FK_09e17479124d09dcf7f902ceaed\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_f32dd66b36a5aa53fc615781bed\``);
        await queryRunner.query(`ALTER TABLE \`question\` DROP FOREIGN KEY \`FK_a964c0196f21cf6ffdf994f74f1\``);
        await queryRunner.query(`ALTER TABLE \`question\` DROP FOREIGN KEY \`FK_690af1a3076d6af739aceeb942a\``);
        await queryRunner.query(`ALTER TABLE \`users_cases\` DROP FOREIGN KEY \`FK_98b89d0b95421aa0ffe4d81e707\``);
        await queryRunner.query(`ALTER TABLE \`users_cases\` DROP FOREIGN KEY \`FK_b5003f35ff1897c040601e6f94b\``);
        await queryRunner.query(`ALTER TABLE \`prosecution\` DROP FOREIGN KEY \`FK_35e459115b61ef26b5bd7ebf8bd\``);
        await queryRunner.query(`ALTER TABLE \`prosecution\` DROP FOREIGN KEY \`FK_5bdaf8b238611ba479f191aac28\``);
        await queryRunner.query(`ALTER TABLE \`indictments\` DROP FOREIGN KEY \`FK_e878e3d70a2832e213b99d83418\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` DROP FOREIGN KEY \`FK_d9cb669d0d27e010b2de18c0c26\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` DROP FOREIGN KEY \`FK_92c1150980585ee7101b6ed070b\``);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` DROP FOREIGN KEY \`FK_337aa8dba227a1fe6b73998307b\``);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` DROP FOREIGN KEY \`FK_7d2dad9f14eddeb09c256fea719\``);
        await queryRunner.query(`ALTER TABLE \`case_result\` DROP FOREIGN KEY \`FK_3b10801e5e42440921e98c8a13e\``);
        await queryRunner.query(`ALTER TABLE \`timelines\` DROP FOREIGN KEY \`FK_c68fc59db25dc3ef014846e2c47\``);
        await queryRunner.query(`ALTER TABLE \`sentence\` DROP FOREIGN KEY \`FK_f2c8e38cd954b09b905f3f3a41b\``);
        await queryRunner.query(`ALTER TABLE \`sentence\` DROP FOREIGN KEY \`FK_dffd1c80b8fbed1c13be3574990\``);
        await queryRunner.query(`DROP TABLE \`financial_invest\``);
        await queryRunner.query(`DROP TABLE \`digital_inverts\``);
        await queryRunner.query(`DROP TABLE \`arrest\``);
        await queryRunner.query(`DROP TABLE \`case\``);
        await queryRunner.query(`DROP TABLE \`cases_evidences\``);
        await queryRunner.query(`DROP TABLE \`evidences\``);
        await queryRunner.query(`DROP TABLE \`warrant\``);
        await queryRunner.query(`DROP TABLE \`warrant_result\``);
        await queryRunner.query(`DROP TABLE \`record_info\``);
        await queryRunner.query(`DROP TABLE \`physical_invest\``);
        await queryRunner.query(`DROP TABLE \`measure_surveys\``);
        await queryRunner.query(`DROP TABLE \`forensic_invest\``);
        await queryRunner.query(`DROP TABLE \`evidences_suspects\``);
        await queryRunner.query(`DROP TABLE \`suspect\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP TABLE \`reports_victims\``);
        await queryRunner.query(`DROP TABLE \`victims\``);
        await queryRunner.query(`DROP TABLE \`victim_interview\``);
        await queryRunner.query(`DROP TABLE \`interviews\``);
        await queryRunner.query(`DROP TABLE \`witnesses_interviews\``);
        await queryRunner.query(`DROP TABLE \`witness\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`question\``);
        await queryRunner.query(`DROP TABLE \`users_cases\``);
        await queryRunner.query(`DROP TABLE \`prosecution\``);
        await queryRunner.query(`DROP TABLE \`indictments\``);
        await queryRunner.query(`DROP TABLE \`investigation_plan\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles_permissions\``);
        await queryRunner.query(`DROP TABLE \`permission\``);
        await queryRunner.query(`DROP TABLE \`case_result\``);
        await queryRunner.query(`DROP TABLE \`timelines\``);
        await queryRunner.query(`DROP TABLE \`sentence\``);
    }

}
