import { MigrationInterface, QueryRunner } from "typeorm";

export class DuctinUpdate07071751876245122 implements MigrationInterface {
    name = 'DuctinUpdate07071751876245122'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`FK_d4ce448ecdb3ea3bba1a418256e\` ON \`interviews\``);
        await queryRunner.query(`DROP INDEX \`FK_dab087b7d082364ae58637eafbb\` ON \`interviews\``);
        await queryRunner.query(`DROP INDEX \`FK_bcf2dfbf294d317c771478079a3\` ON \`sentences\``);
        await queryRunner.query(`DROP INDEX \`FK_fee694f8c062dfd8f7162e6bb65\` ON \`timelines\``);
        await queryRunner.query(`CREATE TABLE \`holidays\` (\`holiday_id\` varchar(255) NOT NULL, \`holiday_name\` varchar(255) NOT NULL, \`type_of_holiday\` enum ('federal_holiday', 'states_holiday') NOT NULL, \`date_of_holiday\` timestamp NOT NULL, \`note\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`holiday_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inmates\` (\`inmate_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`assigned_facility\` varchar(255) NOT NULL, \`start_date\` timestamp NOT NULL, \`expected_release\` timestamp NOT NULL, \`health_status\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`inmate_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`cases\` DROP COLUMN \`case_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`refresh_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD \`crime_type\` enum ('Crimes Against Persons', 'Crimes Against Property', 'White-Collar Crimes', 'Cyber Crimes', 'Drug-related Crimes', 'Public Order Crimes') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD \`reporter_incident_relationship\` enum ('Victim', 'Witness', 'Bystander') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`warrants\` ADD \`deadline\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`warrants\` ADD \`status\` enum ('Waiting executing', 'Executing', 'Completed') NOT NULL DEFAULT 'Waiting executing'`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD \`evidence_type\` enum ('Physical Evidence', 'Biological Evidence', 'Trace Evidence', 'Documentary Evidence', 'Digital Evidence') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cases\` ADD \`case_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP COLUMN \`content\``);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD \`content\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP COLUMN \`answer\``);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD \`answer\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP COLUMN \`reliability\``);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD \`reliability\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`description\` enum ('Patrol Officer', 'Censor', 'Investigator', 'Police Chief', 'Forensic Officer', 'Financial Investigator') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`status\` enum ('active', 'inactive') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`create_at\` \`create_at\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`witnesses\` DROP COLUMN \`statement\``);
        await queryRunner.query(`ALTER TABLE \`witnesses\` ADD \`statement\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD \`start_time\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP COLUMN \`severity\``);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD \`severity\` enum ('Minor', 'Moderate', 'Serious', 'Critical') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`reported_at\` \`reported_at\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD \`status\` enum ('Approved', 'Pending', 'Rejected') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`suspects\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`suspects\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`suspects\` DROP COLUMN \`notes\``);
        await queryRunner.query(`ALTER TABLE \`suspects\` ADD \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`evidences\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`timelines\` CHANGE \`start_time\` \`start_time\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`timelines\` CHANGE \`case_result_id\` \`case_result_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cases\` CHANGE \`summary\` \`summary\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cases\` CHANGE \`create_at\` \`create_at\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions_roles\` ADD CONSTRAINT \`FK_3309f5fa8d95935f0701027f2bd\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permissions\`(\`permission_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permissions_roles\` ADD CONSTRAINT \`FK_e08f6859eaac8cbf7f087f64e2b\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_users\` ADD CONSTRAINT \`FK_bca38ed4b5f75421a0a88fb343e\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_users\` ADD CONSTRAINT \`FK_43f00081b361d6ebe3ccef02c60\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` ADD CONSTRAINT \`FK_4b4f741837d684be06705b7db9f\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` ADD CONSTRAINT \`FK_08d804543940a350437a736673e\` FOREIGN KEY (\`created_officer_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_d4ce448ecdb3ea3bba1a418256e\` FOREIGN KEY (\`investigation_plan_id\`) REFERENCES \`investigation_plans\`(\`investigation_plan_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_dab087b7d082364ae58637eafbb\` FOREIGN KEY (\`interviewer_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`forensic_invests\` ADD CONSTRAINT \`FK_370e3b977eab7c896d696c6e7e3\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`measure_surveys\` ADD CONSTRAINT \`FK_f9e279a719b0af429ebe8073d97\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`physical_invests\` ADD CONSTRAINT \`FK_41d9359f23bf11e9c0c63076021\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant_results\` ADD CONSTRAINT \`FK_d297eeaf104320ae0679bf89bdb\` FOREIGN KEY (\`warrant_id\`) REFERENCES \`warrants\`(\`warrant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`financial_invests\` ADD CONSTRAINT \`FK_f2484aae2944a8c6148f4ceec8b\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`digital_invests\` ADD CONSTRAINT \`FK_165c7c95ed29c4cd3c18dfff124\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sentences\` ADD CONSTRAINT \`FK_bcf2dfbf294d317c771478079a3\` FOREIGN KEY (\`case_result_id\`) REFERENCES \`case_results\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timelines\` ADD CONSTRAINT \`FK_fee694f8c062dfd8f7162e6bb65\` FOREIGN KEY (\`case_result_id\`) REFERENCES \`case_results\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_results\` ADD CONSTRAINT \`FK_2192568b40b5a7f499288e1eb5b\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`case_results\` DROP FOREIGN KEY \`FK_2192568b40b5a7f499288e1eb5b\``);
        await queryRunner.query(`ALTER TABLE \`timelines\` DROP FOREIGN KEY \`FK_fee694f8c062dfd8f7162e6bb65\``);
        await queryRunner.query(`ALTER TABLE \`sentences\` DROP FOREIGN KEY \`FK_bcf2dfbf294d317c771478079a3\``);
        await queryRunner.query(`ALTER TABLE \`digital_invests\` DROP FOREIGN KEY \`FK_165c7c95ed29c4cd3c18dfff124\``);
        await queryRunner.query(`ALTER TABLE \`financial_invests\` DROP FOREIGN KEY \`FK_f2484aae2944a8c6148f4ceec8b\``);
        await queryRunner.query(`ALTER TABLE \`warrant_results\` DROP FOREIGN KEY \`FK_d297eeaf104320ae0679bf89bdb\``);
        await queryRunner.query(`ALTER TABLE \`physical_invests\` DROP FOREIGN KEY \`FK_41d9359f23bf11e9c0c63076021\``);
        await queryRunner.query(`ALTER TABLE \`measure_surveys\` DROP FOREIGN KEY \`FK_f9e279a719b0af429ebe8073d97\``);
        await queryRunner.query(`ALTER TABLE \`forensic_invests\` DROP FOREIGN KEY \`FK_370e3b977eab7c896d696c6e7e3\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_dab087b7d082364ae58637eafbb\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_d4ce448ecdb3ea3bba1a418256e\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` DROP FOREIGN KEY \`FK_08d804543940a350437a736673e\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` DROP FOREIGN KEY \`FK_4b4f741837d684be06705b7db9f\``);
        await queryRunner.query(`ALTER TABLE \`cases_users\` DROP FOREIGN KEY \`FK_43f00081b361d6ebe3ccef02c60\``);
        await queryRunner.query(`ALTER TABLE \`cases_users\` DROP FOREIGN KEY \`FK_bca38ed4b5f75421a0a88fb343e\``);
        await queryRunner.query(`ALTER TABLE \`permissions_roles\` DROP FOREIGN KEY \`FK_e08f6859eaac8cbf7f087f64e2b\``);
        await queryRunner.query(`ALTER TABLE \`permissions_roles\` DROP FOREIGN KEY \`FK_3309f5fa8d95935f0701027f2bd\``);
        await queryRunner.query(`ALTER TABLE \`cases\` CHANGE \`create_at\` \`create_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`cases\` CHANGE \`summary\` \`summary\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`timelines\` CHANGE \`case_result_id\` \`case_result_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`timelines\` CHANGE \`start_time\` \`start_time\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`evidences\` CHANGE \`description\` \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`suspects\` DROP COLUMN \`notes\``);
        await queryRunner.query(`ALTER TABLE \`suspects\` ADD \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`suspects\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`suspects\` ADD \`description\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD \`status\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`reported_at\` \`reported_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP COLUMN \`severity\``);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD \`severity\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD \`start_time\` timestamp(0) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`witnesses\` DROP COLUMN \`statement\``);
        await queryRunner.query(`ALTER TABLE \`witnesses\` ADD \`statement\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`create_at\` \`create_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`status\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP COLUMN \`reliability\``);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD \`reliability\` float NULL`);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP COLUMN \`answer\``);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD \`answer\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP COLUMN \`content\``);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD \`content\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cases\` DROP COLUMN \`case_name\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP COLUMN \`evidence_type\``);
        await queryRunner.query(`ALTER TABLE \`warrants\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`warrants\` DROP COLUMN \`deadline\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP COLUMN \`reporter_incident_relationship\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP COLUMN \`crime_type\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`refresh_token\``);
        await queryRunner.query(`ALTER TABLE \`cases\` ADD \`case_number\` int NOT NULL`);
        await queryRunner.query(`DROP TABLE \`inmates\``);
        await queryRunner.query(`DROP TABLE \`holidays\``);
        await queryRunner.query(`CREATE INDEX \`FK_fee694f8c062dfd8f7162e6bb65\` ON \`timelines\` (\`case_result_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_bcf2dfbf294d317c771478079a3\` ON \`sentences\` (\`case_result_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_dab087b7d082364ae58637eafbb\` ON \`interviews\` (\`interviewer_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_d4ce448ecdb3ea3bba1a418256e\` ON \`interviews\` (\`investigation_plan_id\`)`);
    }

}
