import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1751445947936 implements MigrationInterface {
    name = 'Migrations1751445947936'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`timelines\` (\`timeline_id\` varchar(255) NOT NULL, \`case_result_id\` varchar(255) NOT NULL, \`start_time\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`end_time\` timestamp NULL, \`attached_file\` json NULL, \`notes\` varchar(255) NULL, \`activity\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`timeline_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sentences\` (\`sentence_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`case_result_id\` varchar(255) NOT NULL, \`sentence_type\` varchar(255) NOT NULL, \`duration\` varchar(255) NULL, \`condition\` varchar(255) NULL, \`sentencing_date\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`sentence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_result\` (\`case_result_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`report_time\` timestamp NOT NULL, \`report_analyst\` varchar(255) NULL, \`summary\` varchar(255) NULL, \`identify_motive\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`case_result_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`financial_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`record_infors\` (\`record_info_id\` varchar(255) NOT NULL, \`evidence_id\` varchar(255) NOT NULL, \`type_name\` varchar(255) NOT NULL, \`source\` varchar(255) NOT NULL, \`date_collected\` timestamp NOT NULL, \`summary\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`record_info_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`measure_surveys\` (\`measure_survey_id\` varchar(255) NOT NULL, \`type_name\` varchar(255) NOT NULL, \`source\` varchar(255) NULL, \`result\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`measure_survey_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`digital_inverts\` (\`evidence_id\` varchar(255) NOT NULL, \`device_type\` varchar(255) NOT NULL, \`analyst_tool\` varchar(255) NOT NULL, \`result\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission\` (\`permission_id\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles_permissions\` (\`role_id\` varchar(255) NOT NULL, \`permission_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`role_id\`, \`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`role_id\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`suspects_evidences\` (\`suspect_id\` varchar(255) NOT NULL, \`evidence_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`suspect_id\`, \`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`indictments\` (\`indictment_id\` varchar(255) NOT NULL, \`prosecution_id\` varchar(255) NOT NULL, \`content\` varchar(255) NOT NULL, \`issued_at\` datetime NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`indictment_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`prosecution\` (\`prosecution_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`prosecutor_id\` varchar(255) NOT NULL, \`decision\` varchar(255) NOT NULL, \`decision_date\` datetime NOT NULL, \`reason\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`prosecution_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`prosecutions_suspects\` (\`prosecution_id\` varchar(255) NOT NULL, \`suspect_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`prosecution_id\`, \`suspect_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`suspects\` (\`suspect_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`national\` varchar(255) NOT NULL, \`gender\` varchar(255) NOT NULL, \`dob\` timestamp NOT NULL, \`identification\` varchar(255) NULL, \`phonenumber\` varchar(255) NULL, \`description\` text NULL, \`address\` varchar(255) NULL, \`catch_time\` timestamp NOT NULL, \`notes\` text NULL, \`status\` varchar(255) NOT NULL, \`mugshot_url\` varchar(255) NULL, \`fingerprints_hash\` varchar(255) NULL, \`health_status\` varchar(255) NOT NULL, PRIMARY KEY (\`suspect_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports_suspects\` (\`report_id\` varchar(255) NOT NULL, \`suspect_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`report_id\`, \`suspect_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`investigation_plans\` (\`investigation_plan_id\` varchar(255) NOT NULL, \`created_officer_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`deadline_date\` timestamp NOT NULL, \`result\` varchar(255) NULL, \`status\` varchar(255) NULL, \`create_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`plan_content\` text NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`investigation_plan_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`questions\` (\`question_id\` varchar(255) NOT NULL, \`interview_id\` varchar(255) NOT NULL, \`created_by\` varchar(255) NOT NULL, \`content\` varchar(255) NOT NULL, \`answer\` varchar(255) NULL, \`reliability\` int NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`question_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`witness\` (\`witness_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`statement\` text NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`witness_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`witness_interview\` (\`witness_id\` varchar(255) NOT NULL, \`interview_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`witness_id\`, \`interview_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`interviews\` (\`interview_id\` varchar(255) NOT NULL, \`investigation_plan_id\` varchar(255) NOT NULL, \`interviewer_id\` varchar(255) NOT NULL, \`interviewee_id\` varchar(255) NOT NULL, \`type_interviewee\` varchar(255) NOT NULL, \`location\` varchar(255) NOT NULL, \`attached_file\` varchar(255) NOT NULL, \`start_time\` timestamp NOT NULL, \`end_time\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`interview_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`victims_interview\` (\`victim_id\` varchar(255) NOT NULL, \`interview_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`victim_id\`, \`interview_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`victims\` (\`victim_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`injuries\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`victim_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports_victims\` (\`report_id\` varchar(255) NOT NULL, \`victim_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`report_id\`, \`victim_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`report_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`username\` varchar(255) NOT NULL, \`type_report\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`case_location\` varchar(255) NOT NULL, \`reported_at\` timestamp NOT NULL, \`reporter_location\` varchar(255) NOT NULL, \`reporter_fullname\` varchar(255) NOT NULL, \`reporter_email\` varchar(255) NOT NULL, \`reporter_phonenumber\` varchar(255) NULL, \`office_approve_id\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`report_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users_cases\` (\`user_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`responsible\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`user_id\`, \`case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`username\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`avatar_url\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`phonenumber\` varchar(255) NOT NULL, \`create_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`role_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`username\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`forensic_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`lab_name\` varchar(255) NOT NULL, \`report\` varchar(255) NOT NULL, \`result_summary\` varchar(255) NOT NULL, \`received_at\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cases_evidences\` (\`case_id\` varchar(255) NOT NULL, \`evidence_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`case_id\`, \`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warrant_evidences\` (\`warrant_id\` varchar(255) NOT NULL, \`evidence_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`warrant_id\`, \`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`evidences\` (\`evidence_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`measure_survey_id\` varchar(255) NOT NULL, \`warrant_result_id\` varchar(255) NOT NULL, \`report_id\` varchar(255) NOT NULL, \`collected_by\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`collect_at\` datetime NOT NULL, \`current_location\` varchar(255) NOT NULL, \`attach_file\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`digital_invert_id\` varchar(255) NULL, UNIQUE INDEX \`REL_6fab41d05d06ac35dd215c8327\` (\`digital_invert_id\`), PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`physical_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`image_url\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`warrant_result_id\` varchar(255) NULL, UNIQUE INDEX \`REL_ff727fe101025866c5ee33e105\` (\`warrant_result_id\`), PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warrant_result\` (\`warrant_result_id\` varchar(255) NOT NULL, \`warrant_id\` varchar(255) NOT NULL, \`police_response\` varchar(255) NOT NULL, \`location\` varchar(255) NOT NULL, \`notes\` varchar(255) NOT NULL, \`time_active\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`warrant_result_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warrant\` (\`warrant_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`warrant_name\` varchar(255) NOT NULL, \`attached_file\` varchar(255) NOT NULL, \`time_pulish\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`warrant_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cases\` (\`case_id\` varchar(255) NOT NULL, \`case_number\` int NOT NULL, \`type_case\` varchar(255) NOT NULL, \`severity\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`create_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`arrests\` (\`suspect_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`officer_id\` varchar(255) NOT NULL, \`suspect_miranda_signature\` varchar(255) NULL, \`arrest_start_time\` timestamp NOT NULL, \`arrest_end_time\` timestamp NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`suspect_id\`, \`case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event\` (\`event_id\` varchar(255) NOT NULL, \`suspect_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`time_start\` datetime NOT NULL, \`time_end\` datetime NOT NULL, \`event_name\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`event_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inmate\` (\`inmate_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`assigned_facility\` varchar(255) NOT NULL, \`start_date\` datetime NOT NULL, \`expected_release\` datetime NOT NULL, \`health_status\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`inmate_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`timelines\` ADD CONSTRAINT \`FK_fee694f8c062dfd8f7162e6bb65\` FOREIGN KEY (\`case_result_id\`) REFERENCES \`case_result\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sentences\` ADD CONSTRAINT \`FK_6fe4dadf7d06ff8db872a75232c\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sentences\` ADD CONSTRAINT \`FK_bcf2dfbf294d317c771478079a3\` FOREIGN KEY (\`case_result_id\`) REFERENCES \`case_result\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_result\` ADD CONSTRAINT \`FK_67d9f0d73918f987821f07bd7e3\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`financial_invest\` ADD CONSTRAINT \`FK_0adbd65084d113b5117ee21af6a\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`record_infors\` ADD CONSTRAINT \`FK_f2794cf2537ffac047545047eab\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`digital_inverts\` ADD CONSTRAINT \`FK_e5125b808e73f90db7690af2d17\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` ADD CONSTRAINT \`FK_7d2dad9f14eddeb09c256fea719\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` ADD CONSTRAINT \`FK_337aa8dba227a1fe6b73998307b\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permission\`(\`permission_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suspects_evidences\` ADD CONSTRAINT \`FK_6770815c097189ac93519e6da6a\` FOREIGN KEY (\`suspect_id\`) REFERENCES \`suspects\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suspects_evidences\` ADD CONSTRAINT \`FK_09b42cc05a02a36ad6afb38bdcf\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`indictments\` ADD CONSTRAINT \`FK_2e75b88bc52fc782b8885a3861a\` FOREIGN KEY (\`prosecution_id\`) REFERENCES \`prosecution\`(\`prosecution_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecution\` ADD CONSTRAINT \`FK_3a8429560bba0d190b5e50e66b4\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecution\` ADD CONSTRAINT \`FK_b935d6a7f915ca4b4c5dab4586b\` FOREIGN KEY (\`prosecutor_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecutions_suspects\` ADD CONSTRAINT \`FK_325cb88707315e38fd6a69b8821\` FOREIGN KEY (\`suspect_id\`) REFERENCES \`suspects\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecutions_suspects\` ADD CONSTRAINT \`FK_a76df2e1e49af31c6a1e7a6eeaa\` FOREIGN KEY (\`prosecution_id\`) REFERENCES \`prosecution\`(\`prosecution_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suspects\` ADD CONSTRAINT \`FK_3ebd20f309174d63ab3bab32217\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_suspects\` ADD CONSTRAINT \`FK_e99b111bd1085d425d1d8a0b2b9\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_suspects\` ADD CONSTRAINT \`FK_2c0371c84338f0bd821b03b1803\` FOREIGN KEY (\`suspect_id\`) REFERENCES \`suspects\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` ADD CONSTRAINT \`FK_4b4f741837d684be06705b7db9f\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` ADD CONSTRAINT \`FK_08d804543940a350437a736673e\` FOREIGN KEY (\`created_officer_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD CONSTRAINT \`FK_6024b110ce4990aa1feb1386e0e\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD CONSTRAINT \`FK_7d0fdceddfeebcc65d61b2f4c70\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witness\` ADD CONSTRAINT \`FK_e015cf2f0c2483d0d96859752cb\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witness_interview\` ADD CONSTRAINT \`FK_d3f37c99f36d5a9532237da69f1\` FOREIGN KEY (\`witness_id\`) REFERENCES \`witness\`(\`witness_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witness_interview\` ADD CONSTRAINT \`FK_7ab705cf1fe6ffef08fdbc426f0\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_dab087b7d082364ae58637eafbb\` FOREIGN KEY (\`interviewer_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_d4ce448ecdb3ea3bba1a418256e\` FOREIGN KEY (\`investigation_plan_id\`) REFERENCES \`investigation_plans\`(\`investigation_plan_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victims_interview\` ADD CONSTRAINT \`FK_cf7c0abd2e182cbdcad7477b9b8\` FOREIGN KEY (\`victim_id\`) REFERENCES \`victims\`(\`victim_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victims_interview\` ADD CONSTRAINT \`FK_5d04e30a93b7aea6fd9d8615c59\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victims\` ADD CONSTRAINT \`FK_2c8f627ebbbf8d6575405e49291\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` ADD CONSTRAINT \`FK_005995a69fa262fcbb618eb6bb1\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` ADD CONSTRAINT \`FK_90a054f200e833bea72c588832b\` FOREIGN KEY (\`victim_id\`) REFERENCES \`victims\`(\`victim_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_2bf0a235fc1ba847ded9a311a00\` FOREIGN KEY (\`username\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_a682c128870ee570acccda5abef\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_cases\` ADD CONSTRAINT \`FK_98b89d0b95421aa0ffe4d81e707\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_cases\` ADD CONSTRAINT \`FK_b5003f35ff1897c040601e6f94b\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`forensic_invest\` ADD CONSTRAINT \`FK_d61c030165b7c47929ed72484a4\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` ADD CONSTRAINT \`FK_89100b6fee543b3f09387a723cf\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` ADD CONSTRAINT \`FK_d19f904c25cf4470e88887751a0\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant_evidences\` ADD CONSTRAINT \`FK_a9801e2bbae4bdc86d1087fabee\` FOREIGN KEY (\`warrant_id\`) REFERENCES \`warrant\`(\`warrant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant_evidences\` ADD CONSTRAINT \`FK_5c77f2b1f63950f5d6ee00a35e6\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_35afe40fcc467d5b75116574f6c\` FOREIGN KEY (\`measure_survey_id\`) REFERENCES \`measure_surveys\`(\`measure_survey_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_6fab41d05d06ac35dd215c83273\` FOREIGN KEY (\`digital_invert_id\`) REFERENCES \`digital_inverts\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_025a63c9d883d2024ab9f254ed6\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_59a4f35ec4065da87514e2ab0e5\` FOREIGN KEY (\`collected_by\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_71704a4c6de0f4f2b38bcef53ec\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` ADD CONSTRAINT \`FK_312aa4afe21cae3636897e03212\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` ADD CONSTRAINT \`FK_ff727fe101025866c5ee33e1051\` FOREIGN KEY (\`warrant_result_id\`) REFERENCES \`warrant_result\`(\`warrant_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant_result\` ADD CONSTRAINT \`FK_4f1cb1944d5a8aac75f1f70e3ce\` FOREIGN KEY (\`warrant_id\`) REFERENCES \`warrant\`(\`warrant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant\` ADD CONSTRAINT \`FK_4da374f7725961aec7bbfc0ec0c\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrests\` ADD CONSTRAINT \`FK_83de7623bd3191ecfe107cd21c3\` FOREIGN KEY (\`case_id\`) REFERENCES \`cases\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrests\` ADD CONSTRAINT \`FK_3afeb302fd53fa0d17b00226f18\` FOREIGN KEY (\`suspect_id\`) REFERENCES \`suspects\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`arrests\` DROP FOREIGN KEY \`FK_3afeb302fd53fa0d17b00226f18\``);
        await queryRunner.query(`ALTER TABLE \`arrests\` DROP FOREIGN KEY \`FK_83de7623bd3191ecfe107cd21c3\``);
        await queryRunner.query(`ALTER TABLE \`warrant\` DROP FOREIGN KEY \`FK_4da374f7725961aec7bbfc0ec0c\``);
        await queryRunner.query(`ALTER TABLE \`warrant_result\` DROP FOREIGN KEY \`FK_4f1cb1944d5a8aac75f1f70e3ce\``);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` DROP FOREIGN KEY \`FK_ff727fe101025866c5ee33e1051\``);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` DROP FOREIGN KEY \`FK_312aa4afe21cae3636897e03212\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_71704a4c6de0f4f2b38bcef53ec\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_59a4f35ec4065da87514e2ab0e5\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_025a63c9d883d2024ab9f254ed6\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_6fab41d05d06ac35dd215c83273\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_35afe40fcc467d5b75116574f6c\``);
        await queryRunner.query(`ALTER TABLE \`warrant_evidences\` DROP FOREIGN KEY \`FK_5c77f2b1f63950f5d6ee00a35e6\``);
        await queryRunner.query(`ALTER TABLE \`warrant_evidences\` DROP FOREIGN KEY \`FK_a9801e2bbae4bdc86d1087fabee\``);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` DROP FOREIGN KEY \`FK_d19f904c25cf4470e88887751a0\``);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` DROP FOREIGN KEY \`FK_89100b6fee543b3f09387a723cf\``);
        await queryRunner.query(`ALTER TABLE \`forensic_invest\` DROP FOREIGN KEY \`FK_d61c030165b7c47929ed72484a4\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`users_cases\` DROP FOREIGN KEY \`FK_b5003f35ff1897c040601e6f94b\``);
        await queryRunner.query(`ALTER TABLE \`users_cases\` DROP FOREIGN KEY \`FK_98b89d0b95421aa0ffe4d81e707\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_a682c128870ee570acccda5abef\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_2bf0a235fc1ba847ded9a311a00\``);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` DROP FOREIGN KEY \`FK_90a054f200e833bea72c588832b\``);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` DROP FOREIGN KEY \`FK_005995a69fa262fcbb618eb6bb1\``);
        await queryRunner.query(`ALTER TABLE \`victims\` DROP FOREIGN KEY \`FK_2c8f627ebbbf8d6575405e49291\``);
        await queryRunner.query(`ALTER TABLE \`victims_interview\` DROP FOREIGN KEY \`FK_5d04e30a93b7aea6fd9d8615c59\``);
        await queryRunner.query(`ALTER TABLE \`victims_interview\` DROP FOREIGN KEY \`FK_cf7c0abd2e182cbdcad7477b9b8\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_d4ce448ecdb3ea3bba1a418256e\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_dab087b7d082364ae58637eafbb\``);
        await queryRunner.query(`ALTER TABLE \`witness_interview\` DROP FOREIGN KEY \`FK_7ab705cf1fe6ffef08fdbc426f0\``);
        await queryRunner.query(`ALTER TABLE \`witness_interview\` DROP FOREIGN KEY \`FK_d3f37c99f36d5a9532237da69f1\``);
        await queryRunner.query(`ALTER TABLE \`witness\` DROP FOREIGN KEY \`FK_e015cf2f0c2483d0d96859752cb\``);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP FOREIGN KEY \`FK_7d0fdceddfeebcc65d61b2f4c70\``);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP FOREIGN KEY \`FK_6024b110ce4990aa1feb1386e0e\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` DROP FOREIGN KEY \`FK_08d804543940a350437a736673e\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plans\` DROP FOREIGN KEY \`FK_4b4f741837d684be06705b7db9f\``);
        await queryRunner.query(`ALTER TABLE \`reports_suspects\` DROP FOREIGN KEY \`FK_2c0371c84338f0bd821b03b1803\``);
        await queryRunner.query(`ALTER TABLE \`reports_suspects\` DROP FOREIGN KEY \`FK_e99b111bd1085d425d1d8a0b2b9\``);
        await queryRunner.query(`ALTER TABLE \`suspects\` DROP FOREIGN KEY \`FK_3ebd20f309174d63ab3bab32217\``);
        await queryRunner.query(`ALTER TABLE \`prosecutions_suspects\` DROP FOREIGN KEY \`FK_a76df2e1e49af31c6a1e7a6eeaa\``);
        await queryRunner.query(`ALTER TABLE \`prosecutions_suspects\` DROP FOREIGN KEY \`FK_325cb88707315e38fd6a69b8821\``);
        await queryRunner.query(`ALTER TABLE \`prosecution\` DROP FOREIGN KEY \`FK_b935d6a7f915ca4b4c5dab4586b\``);
        await queryRunner.query(`ALTER TABLE \`prosecution\` DROP FOREIGN KEY \`FK_3a8429560bba0d190b5e50e66b4\``);
        await queryRunner.query(`ALTER TABLE \`indictments\` DROP FOREIGN KEY \`FK_2e75b88bc52fc782b8885a3861a\``);
        await queryRunner.query(`ALTER TABLE \`suspects_evidences\` DROP FOREIGN KEY \`FK_09b42cc05a02a36ad6afb38bdcf\``);
        await queryRunner.query(`ALTER TABLE \`suspects_evidences\` DROP FOREIGN KEY \`FK_6770815c097189ac93519e6da6a\``);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` DROP FOREIGN KEY \`FK_337aa8dba227a1fe6b73998307b\``);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` DROP FOREIGN KEY \`FK_7d2dad9f14eddeb09c256fea719\``);
        await queryRunner.query(`ALTER TABLE \`digital_inverts\` DROP FOREIGN KEY \`FK_e5125b808e73f90db7690af2d17\``);
        await queryRunner.query(`ALTER TABLE \`record_infors\` DROP FOREIGN KEY \`FK_f2794cf2537ffac047545047eab\``);
        await queryRunner.query(`ALTER TABLE \`financial_invest\` DROP FOREIGN KEY \`FK_0adbd65084d113b5117ee21af6a\``);
        await queryRunner.query(`ALTER TABLE \`case_result\` DROP FOREIGN KEY \`FK_67d9f0d73918f987821f07bd7e3\``);
        await queryRunner.query(`ALTER TABLE \`sentences\` DROP FOREIGN KEY \`FK_bcf2dfbf294d317c771478079a3\``);
        await queryRunner.query(`ALTER TABLE \`sentences\` DROP FOREIGN KEY \`FK_6fe4dadf7d06ff8db872a75232c\``);
        await queryRunner.query(`ALTER TABLE \`timelines\` DROP FOREIGN KEY \`FK_fee694f8c062dfd8f7162e6bb65\``);
        await queryRunner.query(`DROP TABLE \`inmate\``);
        await queryRunner.query(`DROP TABLE \`event\``);
        await queryRunner.query(`DROP TABLE \`arrests\``);
        await queryRunner.query(`DROP TABLE \`cases\``);
        await queryRunner.query(`DROP TABLE \`warrant\``);
        await queryRunner.query(`DROP TABLE \`warrant_result\``);
        await queryRunner.query(`DROP INDEX \`REL_ff727fe101025866c5ee33e105\` ON \`physical_invest\``);
        await queryRunner.query(`DROP TABLE \`physical_invest\``);
        await queryRunner.query(`DROP INDEX \`REL_6fab41d05d06ac35dd215c8327\` ON \`evidences\``);
        await queryRunner.query(`DROP TABLE \`evidences\``);
        await queryRunner.query(`DROP TABLE \`warrant_evidences\``);
        await queryRunner.query(`DROP TABLE \`cases_evidences\``);
        await queryRunner.query(`DROP TABLE \`forensic_invest\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`users_cases\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP TABLE \`reports_victims\``);
        await queryRunner.query(`DROP TABLE \`victims\``);
        await queryRunner.query(`DROP TABLE \`victims_interview\``);
        await queryRunner.query(`DROP TABLE \`interviews\``);
        await queryRunner.query(`DROP TABLE \`witness_interview\``);
        await queryRunner.query(`DROP TABLE \`witness\``);
        await queryRunner.query(`DROP TABLE \`questions\``);
        await queryRunner.query(`DROP TABLE \`investigation_plans\``);
        await queryRunner.query(`DROP TABLE \`reports_suspects\``);
        await queryRunner.query(`DROP TABLE \`suspects\``);
        await queryRunner.query(`DROP TABLE \`prosecutions_suspects\``);
        await queryRunner.query(`DROP TABLE \`prosecution\``);
        await queryRunner.query(`DROP TABLE \`indictments\``);
        await queryRunner.query(`DROP TABLE \`suspects_evidences\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles_permissions\``);
        await queryRunner.query(`DROP TABLE \`permission\``);
        await queryRunner.query(`DROP TABLE \`digital_inverts\``);
        await queryRunner.query(`DROP TABLE \`measure_surveys\``);
        await queryRunner.query(`DROP TABLE \`record_infors\``);
        await queryRunner.query(`DROP TABLE \`financial_invest\``);
        await queryRunner.query(`DROP TABLE \`case_result\``);
        await queryRunner.query(`DROP TABLE \`sentences\``);
        await queryRunner.query(`DROP TABLE \`timelines\``);
    }

}
