import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateDatabaseV11751463897647 implements MigrationInterface {
    name = 'CreateDatabaseV11751463897647'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`sentence\` (\`sentence_id\` varchar(255) NOT NULL, \`sentence_type\` varchar(255) NOT NULL, \`duration\` varchar(255) NULL, \`condition\` varchar(255) NULL, \`sentencing_date\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, \`case_result_id\` varchar(255) NULL, PRIMARY KEY (\`sentence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timelines\` (\`timeline_id\` varchar(255) NOT NULL, \`case_result_id\` varchar(255) NOT NULL, \`start_time\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`end_time\` timestamp NULL, \`attached_file\` json NULL, \`notes\` varchar(255) NULL, \`activity\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`timeline_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_result\` (\`case_result_id\` varchar(255) NOT NULL, \`report_time\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`report_analyst\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`identify_motive\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, PRIMARY KEY (\`case_result_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission\` (\`permission_id\` varchar(255) NOT NULL, \`description\` text NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles_permissions\` (\`role_id\` varchar(255) NOT NULL, \`permission_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`role_id\`, \`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`role_id\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`investigation_plan\` (\`investigation_plan_id\` varchar(255) NOT NULL, \`deadline_date\` timestamp NOT NULL, \`result\` text NULL, \`status\` varchar(255) NULL, \`create_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`plan_content\` text NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, \`user_id\` varchar(255) NULL, PRIMARY KEY (\`investigation_plan_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`indictments\` (\`indictment_id\` varchar(255) NOT NULL, \`content\` varchar(255) NOT NULL, \`issued_at\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`prosecution_id\` varchar(255) NULL, PRIMARY KEY (\`indictment_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`prosecution\` (\`prosecution_id\` varchar(255) NOT NULL, \`decision\` varchar(255) NOT NULL, \`decision_date\` timestamp NOT NULL, \`reason\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, \`user_id\` varchar(255) NULL, PRIMARY KEY (\`prosecution_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users_cases\` (\`user_id\` varchar(255) NOT NULL, \`case_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`user_id\`, \`case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`question\` (\`question_id\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`answer\` text NULL, \`reliability\` float NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`interview_id\` varchar(255) NULL, \`user_id\` varchar(255) NULL, PRIMARY KEY (\`question_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`username\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`avatar_url\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`phone_number\` varchar(255) NOT NULL, \`create_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`role_id\` varchar(255) NULL, PRIMARY KEY (\`username\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`witness\` (\`witness_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`statement\` text NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, PRIMARY KEY (\`witness_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`witnesses_interviews\` (\`interview_id\` varchar(255) NOT NULL, \`witness_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`interview_id\`, \`witness_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`interviews\` (\`interview_id\` varchar(255) NOT NULL, \`type_interviewee\` varchar(255) NOT NULL, \`location\` varchar(255) NOT NULL, \`attached_file\` json NOT NULL, \`start_time\` timestamp NOT NULL, \`end_time\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`interviewer_id\` varchar(255) NULL, \`investigation_plan_id\` varchar(255) NULL, PRIMARY KEY (\`interview_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`victim_interview\` (\`victim_id\` varchar(255) NOT NULL, \`interview_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`victim_id\`, \`interview_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`victims\` (\`victim_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`injuries\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, PRIMARY KEY (\`victim_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports_victims\` (\`report_id\` varchar(255) NOT NULL, \`victim_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`report_id\`, \`victim_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`report_id\` varchar(255) NOT NULL, \`type_report\` varchar(255) NOT NULL, \`severity\` varchar(255) NOT NULL, \`incident_date\` timestamp NOT NULL, \`description\` varchar(255) NULL, \`case_location\` varchar(255) NOT NULL, \`reported_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`reporter_location\` varchar(255) NOT NULL, \`reporter_fullname\` varchar(255) NOT NULL, \`reporter_email\` varchar(255) NOT NULL, \`reporter_phone_number\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`status\` varchar(255) NOT NULL, \`user_id\` varchar(255) NULL, \`case_id\` varchar(255) NULL, PRIMARY KEY (\`report_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`suspect\` (\`suspect_id\` varchar(255) NOT NULL, \`fullname\` varchar(255) NOT NULL, \`national\` varchar(255) NOT NULL, \`gender\` varchar(255) NOT NULL, \`dob\` timestamp NOT NULL, \`identification\` varchar(255) NOT NULL, \`phone_number\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`address\` varchar(255) NOT NULL, \`catch_time\` timestamp NOT NULL, \`notes\` text NULL, \`status\` varchar(255) NOT NULL, \`mugshot_url\` varchar(255) NULL, \`fingerprints_hash\` varchar(255) NOT NULL, \`health_status\` varchar(255) NOT NULL, \`case_id\` varchar(255) NULL, \`report_id\` varchar(255) NULL, PRIMARY KEY (\`suspect_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`evidences_suspects\` (\`evidence_id\` varchar(255) NOT NULL, \`suspect_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`, \`suspect_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`measure_surveys\` (\`measure_survey_id\` varchar(255) NOT NULL, \`type_name\` varchar(255) NOT NULL, \`source\` varchar(255) NULL, \`result\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`evidence_id\` varchar(255) NULL, PRIMARY KEY (\`measure_survey_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`physical_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`image_url\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`record_info\` (\`record_info_id\` varchar(255) NOT NULL, \`type_name\` varchar(255) NOT NULL, \`source\` varchar(255) NOT NULL, \`date_collected\` timestamp NOT NULL, \`summary\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`evidence_id\` varchar(255) NULL, PRIMARY KEY (\`record_info_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warrant_result\` (\`warrant_result_id\` varchar(255) NOT NULL, \`police_response\` varchar(255) NOT NULL, \`location\` varchar(255) NOT NULL, \`notes\` varchar(255) NOT NULL, \`time_active\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`warrant_id\` varchar(255) NULL, PRIMARY KEY (\`warrant_result_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warrant\` (\`warrant_id\` varchar(255) NOT NULL, \`warrant_name\` varchar(255) NOT NULL, \`attached_file\` json NULL, \`time_publish\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, PRIMARY KEY (\`warrant_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`evidences\` (\`evidence_id\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`collected_at\` timestamp NOT NULL, \`current_location\` varchar(255) NOT NULL, \`attach_file\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, \`user_id\` varchar(255) NULL, \`report_id\` varchar(255) NULL, \`warrant_id\` varchar(255) NULL, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cases_evidences\` (\`case_id\` varchar(255) NOT NULL, \`evidence_id\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`case_id\`, \`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case\` (\`case_id\` varchar(255) NOT NULL, \`case_number\` int NOT NULL, \`type_case\` varchar(255) NOT NULL, \`severity\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`create_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`arrest\` (\`arrest_id\` varchar(255) NOT NULL, \`suspect_miranda_signature\` varchar(255) NULL, \`arrest_start_time\` timestamp NOT NULL, \`arrest_end_time\` timestamp NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`case_id\` varchar(255) NULL, \`suspect_id\` varchar(255) NULL, PRIMARY KEY (\`arrest_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`digital_inverts\` (\`evidence_id\` varchar(255) NOT NULL, \`device_type\` varchar(255) NOT NULL, \`analyst_tool\` varchar(255) NOT NULL, \`result\` varchar(255) NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`financial_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`summary\` varchar(255) NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`forensic_invest\` (\`evidence_id\` varchar(255) NOT NULL, \`lab_name\` varchar(255) NOT NULL, \`report\` varchar(255) NOT NULL, \`received_at\` timestamp NOT NULL, \`is_deleted\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`evidence_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`sentence\` ADD CONSTRAINT \`FK_3920ea0b9d59562c16a2ada8fcb\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sentence\` ADD CONSTRAINT \`FK_8fe2ba76f593e088e664c3e8515\` FOREIGN KEY (\`case_result_id\`) REFERENCES \`case_result\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timelines\` ADD CONSTRAINT \`FK_fee694f8c062dfd8f7162e6bb65\` FOREIGN KEY (\`case_result_id\`) REFERENCES \`case_result\`(\`case_result_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_result\` ADD CONSTRAINT \`FK_67d9f0d73918f987821f07bd7e3\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` ADD CONSTRAINT \`FK_7d2dad9f14eddeb09c256fea719\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` ADD CONSTRAINT \`FK_337aa8dba227a1fe6b73998307b\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permission\`(\`permission_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` ADD CONSTRAINT \`FK_5533bce4f9a2e507cfcf905d0c0\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` ADD CONSTRAINT \`FK_2b5a15ab1d5141d419e989789a9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`indictments\` ADD CONSTRAINT \`FK_2e75b88bc52fc782b8885a3861a\` FOREIGN KEY (\`prosecution_id\`) REFERENCES \`prosecution\`(\`prosecution_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecution\` ADD CONSTRAINT \`FK_3a8429560bba0d190b5e50e66b4\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prosecution\` ADD CONSTRAINT \`FK_c0467549511c8ef07739485c7ad\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_cases\` ADD CONSTRAINT \`FK_b5003f35ff1897c040601e6f94b\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_cases\` ADD CONSTRAINT \`FK_98b89d0b95421aa0ffe4d81e707\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question\` ADD CONSTRAINT \`FK_0d18fe3e972f670cdb5a01ef6ae\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question\` ADD CONSTRAINT \`FK_82c53e1db067ff3d6ef17dfd5c4\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witness\` ADD CONSTRAINT \`FK_e015cf2f0c2483d0d96859752cb\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` ADD CONSTRAINT \`FK_395823e5b67b06d5febccbe0bfa\` FOREIGN KEY (\`witness_id\`) REFERENCES \`witness\`(\`witness_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` ADD CONSTRAINT \`FK_bd51fb7805ecb70973e357026e4\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_dab087b7d082364ae58637eafbb\` FOREIGN KEY (\`interviewer_id\`) REFERENCES \`users\`(\`username\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interviews\` ADD CONSTRAINT \`FK_d4ce448ecdb3ea3bba1a418256e\` FOREIGN KEY (\`investigation_plan_id\`) REFERENCES \`investigation_plan\`(\`investigation_plan_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` ADD CONSTRAINT \`FK_6df831d0f480118887381de5a74\` FOREIGN KEY (\`victim_id\`) REFERENCES \`victims\`(\`victim_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` ADD CONSTRAINT \`FK_b35cbf11a70f500cc2adff9c652\` FOREIGN KEY (\`interview_id\`) REFERENCES \`interviews\`(\`interview_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`victims\` ADD CONSTRAINT \`FK_2c8f627ebbbf8d6575405e49291\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` ADD CONSTRAINT \`FK_90a054f200e833bea72c588832b\` FOREIGN KEY (\`victim_id\`) REFERENCES \`victims\`(\`victim_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` ADD CONSTRAINT \`FK_005995a69fa262fcbb618eb6bb1\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_ca7a21eb95ca4625bd5eaef7e0c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_a682c128870ee570acccda5abef\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suspect\` ADD CONSTRAINT \`FK_638e3a35d31ff32aa4f579a851f\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suspect\` ADD CONSTRAINT \`FK_6cb01e17f361324ae24b8df61e0\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` ADD CONSTRAINT \`FK_6d92b4c3140e9fda7d72cb9b687\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` ADD CONSTRAINT \`FK_f043d82d1597061ff85f1595286\` FOREIGN KEY (\`suspect_id\`) REFERENCES \`suspect\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`measure_surveys\` ADD CONSTRAINT \`FK_f9e279a719b0af429ebe8073d97\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` ADD CONSTRAINT \`FK_312aa4afe21cae3636897e03212\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`record_info\` ADD CONSTRAINT \`FK_38d323c929ad38b52231de79cc9\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant_result\` ADD CONSTRAINT \`FK_4f1cb1944d5a8aac75f1f70e3ce\` FOREIGN KEY (\`warrant_id\`) REFERENCES \`warrant\`(\`warrant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warrant\` ADD CONSTRAINT \`FK_4da374f7725961aec7bbfc0ec0c\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_025a63c9d883d2024ab9f254ed6\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_54175007da5c95bfb5be50cdaab\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`username\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_71704a4c6de0f4f2b38bcef53ec\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evidences\` ADD CONSTRAINT \`FK_5d35f288a2b487c7dc107c61e29\` FOREIGN KEY (\`warrant_id\`) REFERENCES \`warrant\`(\`warrant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` ADD CONSTRAINT \`FK_89100b6fee543b3f09387a723cf\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` ADD CONSTRAINT \`FK_d19f904c25cf4470e88887751a0\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrest\` ADD CONSTRAINT \`FK_15229dc865bbf50838922ebc19e\` FOREIGN KEY (\`case_id\`) REFERENCES \`case\`(\`case_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrest\` ADD CONSTRAINT \`FK_427d9ef792d99b3c3110efe4c5f\` FOREIGN KEY (\`suspect_id\`) REFERENCES \`suspect\`(\`suspect_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`digital_inverts\` ADD CONSTRAINT \`FK_e5125b808e73f90db7690af2d17\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`financial_invest\` ADD CONSTRAINT \`FK_0adbd65084d113b5117ee21af6a\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`forensic_invest\` ADD CONSTRAINT \`FK_d61c030165b7c47929ed72484a4\` FOREIGN KEY (\`evidence_id\`) REFERENCES \`evidences\`(\`evidence_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`forensic_invest\` DROP FOREIGN KEY \`FK_d61c030165b7c47929ed72484a4\``);
        await queryRunner.query(`ALTER TABLE \`financial_invest\` DROP FOREIGN KEY \`FK_0adbd65084d113b5117ee21af6a\``);
        await queryRunner.query(`ALTER TABLE \`digital_inverts\` DROP FOREIGN KEY \`FK_e5125b808e73f90db7690af2d17\``);
        await queryRunner.query(`ALTER TABLE \`arrest\` DROP FOREIGN KEY \`FK_427d9ef792d99b3c3110efe4c5f\``);
        await queryRunner.query(`ALTER TABLE \`arrest\` DROP FOREIGN KEY \`FK_15229dc865bbf50838922ebc19e\``);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` DROP FOREIGN KEY \`FK_d19f904c25cf4470e88887751a0\``);
        await queryRunner.query(`ALTER TABLE \`cases_evidences\` DROP FOREIGN KEY \`FK_89100b6fee543b3f09387a723cf\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_5d35f288a2b487c7dc107c61e29\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_71704a4c6de0f4f2b38bcef53ec\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_54175007da5c95bfb5be50cdaab\``);
        await queryRunner.query(`ALTER TABLE \`evidences\` DROP FOREIGN KEY \`FK_025a63c9d883d2024ab9f254ed6\``);
        await queryRunner.query(`ALTER TABLE \`warrant\` DROP FOREIGN KEY \`FK_4da374f7725961aec7bbfc0ec0c\``);
        await queryRunner.query(`ALTER TABLE \`warrant_result\` DROP FOREIGN KEY \`FK_4f1cb1944d5a8aac75f1f70e3ce\``);
        await queryRunner.query(`ALTER TABLE \`record_info\` DROP FOREIGN KEY \`FK_38d323c929ad38b52231de79cc9\``);
        await queryRunner.query(`ALTER TABLE \`physical_invest\` DROP FOREIGN KEY \`FK_312aa4afe21cae3636897e03212\``);
        await queryRunner.query(`ALTER TABLE \`measure_surveys\` DROP FOREIGN KEY \`FK_f9e279a719b0af429ebe8073d97\``);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` DROP FOREIGN KEY \`FK_f043d82d1597061ff85f1595286\``);
        await queryRunner.query(`ALTER TABLE \`evidences_suspects\` DROP FOREIGN KEY \`FK_6d92b4c3140e9fda7d72cb9b687\``);
        await queryRunner.query(`ALTER TABLE \`suspect\` DROP FOREIGN KEY \`FK_6cb01e17f361324ae24b8df61e0\``);
        await queryRunner.query(`ALTER TABLE \`suspect\` DROP FOREIGN KEY \`FK_638e3a35d31ff32aa4f579a851f\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_a682c128870ee570acccda5abef\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_ca7a21eb95ca4625bd5eaef7e0c\``);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` DROP FOREIGN KEY \`FK_005995a69fa262fcbb618eb6bb1\``);
        await queryRunner.query(`ALTER TABLE \`reports_victims\` DROP FOREIGN KEY \`FK_90a054f200e833bea72c588832b\``);
        await queryRunner.query(`ALTER TABLE \`victims\` DROP FOREIGN KEY \`FK_2c8f627ebbbf8d6575405e49291\``);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` DROP FOREIGN KEY \`FK_b35cbf11a70f500cc2adff9c652\``);
        await queryRunner.query(`ALTER TABLE \`victim_interview\` DROP FOREIGN KEY \`FK_6df831d0f480118887381de5a74\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_d4ce448ecdb3ea3bba1a418256e\``);
        await queryRunner.query(`ALTER TABLE \`interviews\` DROP FOREIGN KEY \`FK_dab087b7d082364ae58637eafbb\``);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` DROP FOREIGN KEY \`FK_bd51fb7805ecb70973e357026e4\``);
        await queryRunner.query(`ALTER TABLE \`witnesses_interviews\` DROP FOREIGN KEY \`FK_395823e5b67b06d5febccbe0bfa\``);
        await queryRunner.query(`ALTER TABLE \`witness\` DROP FOREIGN KEY \`FK_e015cf2f0c2483d0d96859752cb\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`question\` DROP FOREIGN KEY \`FK_82c53e1db067ff3d6ef17dfd5c4\``);
        await queryRunner.query(`ALTER TABLE \`question\` DROP FOREIGN KEY \`FK_0d18fe3e972f670cdb5a01ef6ae\``);
        await queryRunner.query(`ALTER TABLE \`users_cases\` DROP FOREIGN KEY \`FK_98b89d0b95421aa0ffe4d81e707\``);
        await queryRunner.query(`ALTER TABLE \`users_cases\` DROP FOREIGN KEY \`FK_b5003f35ff1897c040601e6f94b\``);
        await queryRunner.query(`ALTER TABLE \`prosecution\` DROP FOREIGN KEY \`FK_c0467549511c8ef07739485c7ad\``);
        await queryRunner.query(`ALTER TABLE \`prosecution\` DROP FOREIGN KEY \`FK_3a8429560bba0d190b5e50e66b4\``);
        await queryRunner.query(`ALTER TABLE \`indictments\` DROP FOREIGN KEY \`FK_2e75b88bc52fc782b8885a3861a\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` DROP FOREIGN KEY \`FK_2b5a15ab1d5141d419e989789a9\``);
        await queryRunner.query(`ALTER TABLE \`investigation_plan\` DROP FOREIGN KEY \`FK_5533bce4f9a2e507cfcf905d0c0\``);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` DROP FOREIGN KEY \`FK_337aa8dba227a1fe6b73998307b\``);
        await queryRunner.query(`ALTER TABLE \`roles_permissions\` DROP FOREIGN KEY \`FK_7d2dad9f14eddeb09c256fea719\``);
        await queryRunner.query(`ALTER TABLE \`case_result\` DROP FOREIGN KEY \`FK_67d9f0d73918f987821f07bd7e3\``);
        await queryRunner.query(`ALTER TABLE \`timelines\` DROP FOREIGN KEY \`FK_fee694f8c062dfd8f7162e6bb65\``);
        await queryRunner.query(`ALTER TABLE \`sentence\` DROP FOREIGN KEY \`FK_8fe2ba76f593e088e664c3e8515\``);
        await queryRunner.query(`ALTER TABLE \`sentence\` DROP FOREIGN KEY \`FK_3920ea0b9d59562c16a2ada8fcb\``);
        await queryRunner.query(`DROP TABLE \`forensic_invest\``);
        await queryRunner.query(`DROP TABLE \`financial_invest\``);
        await queryRunner.query(`DROP TABLE \`digital_inverts\``);
        await queryRunner.query(`DROP TABLE \`arrest\``);
        await queryRunner.query(`DROP TABLE \`case\``);
        await queryRunner.query(`DROP TABLE \`cases_evidences\``);
        await queryRunner.query(`DROP TABLE \`evidences\``);
        await queryRunner.query(`DROP TABLE \`warrant\``);
        await queryRunner.query(`DROP TABLE \`warrant_result\``);
        await queryRunner.query(`DROP TABLE \`record_info\``);
        await queryRunner.query(`DROP TABLE \`physical_invest\``);
        await queryRunner.query(`DROP TABLE \`measure_surveys\``);
        await queryRunner.query(`DROP TABLE \`evidences_suspects\``);
        await queryRunner.query(`DROP TABLE \`suspect\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP TABLE \`reports_victims\``);
        await queryRunner.query(`DROP TABLE \`victims\``);
        await queryRunner.query(`DROP TABLE \`victim_interview\``);
        await queryRunner.query(`DROP TABLE \`interviews\``);
        await queryRunner.query(`DROP TABLE \`witnesses_interviews\``);
        await queryRunner.query(`DROP TABLE \`witness\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`question\``);
        await queryRunner.query(`DROP TABLE \`users_cases\``);
        await queryRunner.query(`DROP TABLE \`prosecution\``);
        await queryRunner.query(`DROP TABLE \`indictments\``);
        await queryRunner.query(`DROP TABLE \`investigation_plan\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles_permissions\``);
        await queryRunner.query(`DROP TABLE \`permission\``);
        await queryRunner.query(`DROP TABLE \`case_result\``);
        await queryRunner.query(`DROP TABLE \`timelines\``);
        await queryRunner.query(`DROP TABLE \`sentence\``);
    }

}
